site_name: "Landing pages of Kurt Lust"
site_url: https://klust.github.io/
site_dir: site
site_description: >-
  Home page and GitHub landing page of Kurt Lust

theme:
  name: material
  # We'll customise the team (basically a simpler footer)
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
  palette:
    - primary: black

#hide:
#  - toc

nav:
  - About me: 
    - index.md
    - CV: CV.md
    - Links: links.md
  - Supercomputers for Starters: SupercomputersForStarters
  - LUMI-BE trainings: LUMI-BE-training-materials
  - Win for HPC: windows-client-HPC
  - macOS to Linux: macos-to-linux
  - LUMI tips&tricks: LUMI-tips-and-tricks
  - EasyBuild for LUMI trainings: easybuild-tutorial

plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # redirects for shorter entries to pages in subsites.
  - redirects:
      redirect_maps:
          intro-evolving.md: https://klust.github.io/LUMI-BE-training-materials/intro-evolving/
          update-202409.md: https://klust.github.io/LUMI-training-materials/User-Updates/Update-202409/
          EPICURE.md: https://klust.github.io/EPICURE-meetings/20241202-Brussels/
          EPICURE2024.md: https://klust.github.io/EPICURE-meetings/20241202-Brussels/
          Armes.md: https://maps.app.goo.gl/TJroSYKefBcMQbnu6
          armes.md: https://maps.app.goo.gl/TJroSYKefBcMQbnu6
          zoom.md: https://cscfi.zoom.us/j/3432837620?pwd=eEdNT2hlQmZEYXcrUkZad3BBTjNLdz09

markdown_extensions:
  - meta
  # Nicer tables
  - tables
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: false
      toc_depth: 3

extra_css:
  - stylesheets/extra.css

extra:
  # add links in bottom right
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/klust
      name: Kurt Lust on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/kurtlust
      name: Kurt Lust on LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC3szWMS7glcfWsEZTZXQ1oQ
      name: Work-related YouTube channel of Kurt Lust
