site_name: "Landing pages of Kurt Lust"
site_url: https://klust.github.io/
site_dir: site
site_description: >-
  Home page and GitHub landing page of Kurt Lust

theme:
  name: material
  # We'll customise the team (basically a simpler footer)
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
  palette:
    - primary: black

#hide:
#  - toc

nav:
  - About me: 
    - index.md
    - CV: CV.md
    - Links: links.md
  - Supercomputers for Starters: SupercomputersForStarters
  - Win for HPC: windows-client-HPC
  - Missing Cray manual: cray-missing-manual
  - EasyBuild for LUMI training: easybuild-tutorial

plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized

markdown_extensions:
  - meta
  # Nicer tables
  - tables
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: false
      toc_depth: 3

extra_css:
  - stylesheets/extra.css

extra:
  # add links in bottom right
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/klust
      name: Kurt Lust on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/kurtlust
      name: Kurt Lust onb LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC3szWMS7glcfWsEZTZXQ1oQ
      name: Work-related YouTube channel of Kurt Lust
